### ISSUE TITLE
Where can I find CLIP-MLD-Adapter mode in MMM-CLIP-PP repository pls?

### ISSUE THREAD

**Issue by canornot** [CV-Magician/MMM-CLIP#1]
Could anyone help indicate how I can find the CLIP-MLD-Adapter mode in the MMM-CLIP-PP repository pls? It seems the MMM-CLIP-PP repository is essentially about OpenCLIP, which is so wide that implementation of CLIP-MLD-Adapter can hardly be located. Thank you very much!

麻烦作者或者有人能够帮忙指明一下在MMM-CLIP-PP库里怎样能找到CLIP-MLD-Adapter mode吗？好像MMM-CLIP-PP库就是涵盖面比较广的OpenCLIP，很难定位到CLIP-MLD-Adapter的执行代码部分。非常感谢作者和大家帮忙啦！

**Comment by YesianRohn** [comment]
你可以查看commit记录，获取代码更改部分
https://github.com/CV-Magician/MMM-CLIP-PP/commit/b7b00455e4a12a3004c9b03c2344501f210fe87a

**Comment by canornot** [comment]
看到了看到了 灰常感谢作者！:-)

**Comment by lingqiaoZ** [comment]
> 看到了看到了 灰常感谢作者！:-)

请问能否提供一下CLIP-MLD-Adapter mode 的代码？（本人小白，不知道如何实现）非常感谢！！！

**Comment by YesianRohn** [comment]
查看 commit 记录中的 model.py 文件
