### ISSUE TITLE
In MMM-CLIP-PP the open-source parameter train_vitl_coco.sh cannot reproduce CLIP-MLD-Adapter. mAP around 0.03 only

### ISSUE THREAD

**Issue by canornot** [CV-Magician/MMM-CLIP#2]
用MMM-CLIP-PP代码不知大家能够复现出paper里的CLIP-MLD-Adapter方案下Kaggle-Test-0.3的99.8%或VOC2007-Test的92.6%不？目前代码里src/scripts/train_vitl_coco.sh好像不是最新的参数表啊？以参数表里的learning_rate 0.01在coco_train数据集上训练，最后mAP只有3.67%左右，达不到90以上。

我调了下，按paper说的把learning_rate调到0.001，模型AdaptedCLIP里只用一个TransformerDecoderBlock，在coco_train数据集上训练了1000多个epoch，在coco_val上才达到79%左右（没有overfitting，测了300/500/700/900 epoch coco_val_mAP都在递增），没有实现paper里说的训练180 epoch后mAP到达90%多。

不知哪位大神能给些指点不？或者作者更新一份有效的参数表不？提前谢谢大家啦！

**Comment by canornot** [comment]
啊 发现是我overfitting了 在300个epoch, coco_val_mAP已经到达了最好的81.17% 在1000多个epoch overfitting所掉到了79% 虽然paper里没有列出coco_val的最佳的mAP 但至少比CLIP-FC-Adapter的mAP 73.2%要好 多谢大家！

友情提醒大家，要复现需要把AdaptedCLIP里的decoder_1和decoder_2去掉，同时learning_rate调到0.001，基本就能复现成功了

**Comment by YesianRohn** [comment]
@Row11n  我帮你at一下作者吧，这部分是他完成的
